// Function prototypes
void gps_setup();
void gps_read();
void updateDisplay();
void guidance();
void drive_setup();
void servo_setup();
void display_setup();
void processGPSData();
void manual_control();
void man_con_setup();
void controlCheck();
void sd_card_setup();
void data_record();
void debug_print();
void power_setup();
void power_control();
void servo_control();
void power_readings();
void thermal_setup();
void thermal_sensors();
void bluetooth_setup();
void bluetoothRX();
void speakerSetup();
void drive_control();
void new_data_file();
void satcom_setup();
void motion_setup();
void motion_read();
void bt_main_menu();
void transmit_sbd();
void sat_com_RX();
void thermal_sensor_setup();
void check_thermal();
void dualFeedback(String message);
void dualFeedbackln(String message);